### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by nadavrot**
This commit adds a docker file that builds the Minotaur project.

To build the container use:

  docker build -t llvmdev -f Dockerfile .

To run the container use:

  docker run -it llvmdev bash

### CODE REVIEW

**Comment by nadavrot** [comment]
@zhengyang92 @regehr Would this be useful?

**Comment by zhengyang92** [comment]
Hi Nadav,

Thanks a lot for the patch! I didn't notice your PR (and I've created my own version of Dockerfile in the meantime) until you left the comment. It is weird that Github does not send out notification emails for PRs, I need to check the repo settings.

It seems your version is better than mine so I'll merge and replace mine.

-zhengyang

**Comment by nadavrot** [comment]
Thank you @zhengyang92 !

**Comment by regehr** [comment]
also @nadavrot if anyone at your org is using Minotaur we'd love to learn more about this

**Pull request merged**
